name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build
        run: ./gradlew build

      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: libs
          path: build/libs

      - name: Archive test report
        uses: actions/upload-artifact@v1
        if: ${{ !cancelled() }}
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationsToGithubPackagesRepository
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
